# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp list
#'
#' using an Rcpp function to create a list
#'
#' @return list
#' @examples
#' rcpp_hello()
#' @export
rcpp_hello <- function() {
    .Call('firstpackage_rcpp_hello', PACKAGE = 'firstpackage')
}

